### ISSUE TITLE
Issue with src/ project resolution when setuptools module is defined

### ISSUE THREAD

**Issue by joshua-auchincloss** [joshua-auchincloss/hatch-cython#20]
eg. 

```toml
[tools.setuptools]
py-modules = ["abclib"]
```

Err: `abclib/abc.so does not exist`

Expected: `src/abclib/...`

Temporary fix: remove `tools.setuptools` when building with hatch
