### ISSUE TITLE
External cpp files will be deleted when compilation failed 

### ISSUE THREAD

**Issue by ChingChuan-Chen** [joshua-auchincloss/hatch-cython#27]
My package is like below:

``` shell
$ tree .
.
├── poc
│   ├── __init__.py
│   ├── cpp_helper.cpp
│   ├── cpp_helper.h
│   └── do_stuff.pyx
├── README.rst
├── MANIFEST.in
└── pyproject.toml
```

The `cpp_helper.cpp` will be deleted if my code failed to compile.
It looks like that it clearn up every `cpp` and `c` files.
Coud please you help fix it?

**Comment by joshua-auchincloss** [comment]
Apologies for the delayed reponse - you should be able to exclude the file from any actions (i.e preserve all `cpp` artifacts) if you do something like the following:

```toml
# hatch.toml

[build.hooks.cython.options]
# these might be NRQ
env = [{ env = "CPPFLAGS", arg = "-I./poc", platforms = "*", arch = "*" }]
extra_link_args = [{ arg = "-L./poc", platforms = "*", arch = "*" }]

[build.hooks.cython.options.files]
# this would be required
exclude = [{ matches = "*.cpp" }, { matches = "*/*.cpp" }]

```

You would then want to `cimport` the `cpp_helper.h` in your `do_stuff.pyx`. Let me know if this works and I'll tag this appropriately :)
