### ISSUE TITLE
Failed getting this to work

### ISSUE THREAD

**Issue by itamarst** [joshua-auchincloss/hatch-cython#45]
I was very glad to see this existed but I cannot figure how to use it.

I want to have a `.py` file that is both importable from Python and compiled via Cython (so we can distribute source-only wheel as fallback). With setuptools I would try something like this:

```
from setuptools import setup, Extension
from Cython.Build import cythonize

setup(
    ext_modules=cythonize(
        [
            Extension(
                "twisted.internet._deferred_cython",
                sources=["src/twisted/internet/_deferred_base.py"],
            )
        ]
    )
)
```

Unfortunately I can't figure how one would do this with the current config format. I am particularly confused by the fact that there's no way to list which files an extension should have, or at least no documented way. My initial attempts resulted in every single `.py` file being compiled as an extension, which is probably not ideal :grin: 

Any help would be appreciated.

**Comment by ofek** [comment]
Can you show examples of configuration that you have tried?

**Comment by joshua-auchincloss** [comment]
Appreciate the time to detail your use case, much appreciated.

As @ofek mentioned, a config reference would be helpful - if I'm understanding your use case properly though, your aim is to compile the python files _only_ specified by what you declare in the configuration? At this time, there is only an exclude implementation; that being said I'm happy to implement / accept PRs if it's a needed feature 👍

**Comment by joshua-auchincloss** [comment]
Hey @itamarst - v0.6.0rc0 is released, feel free to try it out. Let me know if there are any issues with the build & will work to have the final v0.6.0 suit the needs of your use case.

Based on the above, you'll want a config like:

```toml
# hatch.toml

[build.targets.wheel]
macos-max-compat = false
packages = ["twisted"]

[build.hooks.cython]
dependencies = [
  "hatch-cython>=0.6.0rc0"
]

[build.hooks.cython.options]
src = "twisted"

[build.hooks.cython.options.files]
aliases = {"twisted.internet._deferred_base" = "twisted.internet._deferred_cython"}
targets = ["*/internet/_deferred_base.py"]
```
